- name: Init K8s
  become: true
  shell: kubeadm init --apiserver-advertise-address "{{ ansible_host }}" --node-name "{{ inventory_hostname }}" --pod-network-cidr=10.17.0.0/16

- name: Create .kube directory
  become: true
  file:
    path: /home/{{ ansible_user }}/.kube
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Copy k8s config
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: Install Calico
  shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
  #environment:
  #  KUBECONFIG: /etc/kubernetes/admin.conf

- name: Download Calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
    dest: ./calico.yaml

- name: Fix Calico network range
  replace:
    path: ./calico.yaml
    regexp: '192.168.0.0'
    replace: '10.17.0.0'

- name: Apply Calico manifest
  shell: kubectl apply -f calico.yaml

- name: Remove Calico manifest
  file:
    path: ./calico.yaml
    state: absent

- name: Get Join command
  shell: kubeadm token create --print-join-command
  register: k8sjc

- name: Register Join command
  set_fact:
    kubernetes_join_command: "{{ k8sjc.stdout }}"
